spring.application.name=food-delivery-api

# Datasource - SQLite
spring.datasource.url=jdbc:sqlite:food-delivery.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:Zm9vZC1kZWxpdmVyeS1hcGktc2VjcmV0LWtleS1wYXJhLWRlc2Vudm9sdmltZW50bw}
jwt.expiration=86400000
